### ISSUE TITLE
Decisions for Russian expansion into German Poland and East Prussia

### ISSUE THREAD

**Issue by AFP595** [SighPie/HFM#128]
A time ago I played a Russian campaign where I managed to take over the whole two states of Austrian Galicia (including Krakow) but I only managed to core the eastern state that is filled with Ukrainians. This is not coherent with the fact that Russia has cores on all of Congress Poland, which starts basically only with Poles in its territory. And furthermore, I have seen an ambitious AI Russia take over Ostpreussen, only to lose it shortly after their war because hundreds of thousands of rebels sprung up and took over the state, immediately returning it to Prussia.
Hence, I think that there should be a set of special decisions allowing mid/late-game Russia to quickly integrate parts of Poland and East Prussia, and realise special strategic interests that might have arisen historically. Here are some suggestions:

1) **"Integrate Galicia-Lodomeria":** If Russia is an absolute/semi-constitutional monarchy controlled by conservatives or reactionaries, has researched _State and Government_, and owns and controls all core provinces of Galicia-Lodomeria (the country), either _add cores_ OR _add the Core Integration modifier_, whichever is less OP.

2) **"Embrace the Poles":** If Russia is a constitutional monarchy with Liberals in power, has researched _Nationalism and Imperialism_, and has cores over all of the former Congress Poland AND Galicia-Lodomeria, add Polish as an accepted culture.

3) **"Integrate Posen/Silesia/Pomerelia":** This would be a set of three similar decisions, all which would only be available if Polish was an accepted culture. They would require to have researched _Revolution and Counterrevolution_, and for the cores of the namesake Polish-culture countries to be either owned by Russia, or its owner be a Russian satellite or Sphere-of-Influence member. If the targeted countries were those very tags (Posen/Silesia/Pomerelia) then they would be inherited by Russia, and then it would either _add cores_ OR _add Core Integration_ to their provinces. If the targeted countries aren't one of those (i.e. a Prussia/Germany kicked so hard they descended below GP status) then the states with the cores of the namesake countries would be transferred to Russia, and it would either _add cores_ OR _add Core Integration_ to the transferred provinces.

4) **"Establish rule in East Prussia":** If Russia owns and controls the Ostpreussen state and has researched _State and Government_, a new East Prussia tag would have cores added to all of the state's provinces. This tag would have Eastern German as primary culture and North German as accepted culture. Then, an event would pop letting the player decide on how to handle the administration of the newly acquired state: either by releasing the new tag as a puppet country; or by directly incorporating them, adding Eastern German as accepted culture and the _Core Integration_ modifier to all of the state's provinces. The former would anger all non-primary/accepted pops, seeing how certain privileged minorities don't have to live under direct Russian rule; while the latter would anger all conservative/reactionary/fascist(?) pops in Russia, seeing how they let non-Slavic people be considered full citizens of Russia.

(all decisions would require Russia to be at peace, obviously)

Maybe decisions to incorporate further parts of Germany/Austria/Czechoslovakia could be put in place, but these are the only ideas I can be bothered to elaborate as of now.

What do you think about this? Does it sound feasible from a modding/playing perspective? I hope that at least some of it can make it to the mod...

**Comment by Suprcheese** [comment]
I definitely agree that a decision to Integrate Galicia-Lodomeria is needed for a successful Russian Empire, due to the large population of Ukrainians there. However, adding Polish as an accepted culture may well be a bridge too far. 
Furthermore, acquiring cores in eastern regions of Prussia should be a very slow process, and require vast resettlement campaigns. 
Russian expansionism into further regions of Prussia & Austria is already covered by the existing "Establish Zapadoslavia" decision, which provides Russia with a strong puppet that can expand into Silesia, Czechoslovakia, and even all the way to Danzig. The only addition I'd consider needed here would be adding Sorbian (Western Slavic) as an accepted culture for Zapadoslavia.

**Comment by SighPie** [comment]
1. There’s already a decision for Russia to claim Galicia.

2., 3., 4. I do not wish to include these

**Comment by SimonWeber** [comment]
@SighPie What about a russian decision that renames Königsberg to [Kaliningrad ](https://en.wikipedia.org/wiki/Kaliningrad) and gives cores?

Due to the [historical expulsion](https://en.wikipedia.org/wiki/Flight_and_expulsion_of_Germans_(1944%E2%80%9350)) it may make sence to put a strong emigration modifier. The destination for these Northern German refugees should be Germany. Around 20% Northern German POP will never arrive and will be removed from the game.

As this decision is rather radical it could cost some infamy, additionally AI just execute it if infamy is 0, tag GER must exist and year > 1880. That prevents a Germany player from loosing his populated homeland instantly in the early game.
